# Generated by Django 5.2.1 on 2025-08-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_new_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_slug',
            new_name='news_slug',
        ),
    ]
